-- USANDO WHERE PARA FILTRAR CATEGORIAS:
SELECT * FROM crime_scene_report WHERE type = 'murder'

-- PARA VER APENAS OS 10 PRIMEIROS DO MURDER:
SELECT * FROM crime_scene_report WHERE type = 'murder' LIMIT 10

-- PARA VER LINHAS COM DATAS ANTES DE 15 DO 01 DE 2018 
SELECT * FROM crime_scene_report WHERE date < 20180115 LIMIT 10

-- PARA FILTRAR APARTIR DE DUAS COLUNAS TEMOS QUE USAR AND. E A SEGUNDA SETENÇA. 
SELECT * FROM crime_scene_report WHERE date < 20180115 AND type = 'murder'

-- PARA FILTRAR APARTIR DE UMA CONDIÇÃO DE FILTRO OU OUTRA:
-- SE TIVER APENAS 1 REQUISITO TAMBEM SERÁ FILTRADO:
-- SEPARAR TIPOS DE CRIMES EM ARSON E MURDER:
SELECT * FROM crime_scene_report WHERE type = 'arson' OR type = 'murder'

-- OUTRA MANEIRA DE SELECIONAR MAIS DE UM TIPO DE CRIME: 
-- USANDO IN E SELECIONANDO TODOS OS TIPOS ESCRITOS DENTRO DO PARENTESES :
SELECT * FROM crime_scene_report  WHERE type IN ('fraud', 'arson', 'murder')

-- UTILIZANDO LIKE PARA PEGAR NOMES PARECIDOS. TIPO VAMOS SUPOR QUE VOCE TEM CHURN_1, CHURN_2 ... CHURN_100
-- VOCE DESEJA PEGAR TODOS QUE SEJAM CHURN, VOCE PODE ESCREVER TODOS OU USAR O LIKE
-- O % SERVE PARA INDICAR QUE O COMEÇO DEVE SER O QUE VOCE DEFINIU E NAO IMPORTAR COM O QUE VEM DEPOIS
-- NO CASO ABAIXO SO VAI APARECER OS DE 2017
SELECT * FROM crime_scene_report WHERE date LIKE '2017%'

-- O LIKE É MUITO MAIS CUSTOSO EM MEMORIA DOS QUE AS COMPARAÇOES FEITAS ASSIM EM IGUALDADE OU USANDO MENOR E MAIOR QUE
-- SE VOCÊ SABE O QUE DE FATO QUER E COMO BUSCAR USE IN, OR E AND E EVITAR O LIKE.
-- A FORMA MENOS CUSTOSA DE TODAS SERIA SOMENTE COM AS IGUALDADES SEM USAR O QUE FOI USADO ACIMA (LIKE, IN E ETC)
