-- USANDO WHERE PARA FILTRAR CATEGORIAS:
SELECT * FROM crime_scene_report WHERE type = 'murder'

-- PARA VER APENAS OS 10 PRIMEIROS DO MURDER:
SELECT * FROM crime_scene_report WHERE type = 'murder' LIMIT 10

-- PARA VER LINHAS COM DATAS ANTES DE 15 DO 01 DE 2018 
SELECT * FROM crime_scene_report WHERE date < 20180115 LIMIT 10

-- PARA FILTRAR APARTIR DE DUAS COLUNAS TEMOS QUE USAR AND. E A SEGUNDA SETENÇA. 
SELECT * FROM crime_scene_report WHERE date < 20180115 AND type = 'murder'

-- PARA FILTRAR APARTIR DE UMA CONDIÇÃO DE FILTRO OU OUTRA:
-- SE TIVER APENAS 1 REQUISITO TAMBEM SERÁ FILTRADO:
-- SEPARAR TIPOS DE CRIMES EM ARSON E MURDER:
SELECT * FROM crime_scene_report WHERE type = 'arson' OR type = 'murder'