-- PARA SELECIONAR TUDO:
SELECT * FROM crime_scene_report 

-- PARA SELECIONAR COLUNAS ESPECIFICAS:
SELECT type, description FROM crime_scene_report

-- PARA SELECIONAR LINHAS ESPECIFICA (USA-SE LIMIT PARA LIMITAR O NUMERO DE LINHAS)
-- OBS: O LIMIT DEVE SEMPRE SER ESCRITO POR ULTIMO
SELECT type, description FROM crime_scene_report LIMIT 10